eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: zuul-feign-consumer
    api-b:
      path: /api-b/**
      serviceId: zuul-ribbon-consumer