spring:
  profiles:
    active: peer1
security:
  basic:
    enabled: true
  user:
    name: admin
    password: 123456
---
server:
  port: 8081



spring:
  application:
    name: register
  profiles: peer1

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:123456@peer2:8082/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

---


server:
  port:  8082


spring:
  application:
    name:  register
  profiles:  peer2

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:123456@peer1:8081/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
