user:
  name: admin
  password: 123456
server:
  port: 8080

spring:
  application:
    name: eureka-hi-service
eureka:
  client:
    service-url:
     defaultZone: http://${user.name}:${user.password}@peer1:8761/eureka/,http://${user.name}:${user.password}@peer2:8762/eureka/, http://${user.name}:${user.password}@peer3:8763/eureka/
