#端口
server:
  port: 8763
spring:
  #安全认证
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: 123456
  #应用名称
  application:
    name: register
  profiles: peer3

eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true #使用ip注册
  client:
    # 表示是否注册自身到eureka服务器(默认：true)
    register-with-eureka: false
    # 是否从eureka上获取注册信息(默认：true)
    fetch-registry: false
    # 查询注册都依赖此地址 默认为http://localhost:8761/eureka 多个地址使用","分割
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8761/eureka/, http://${spring.security.user.name}:${spring.security.user.password}@peer2:8762/eureka/

  server:
    # 安全保护机制
    enable-self-preservation: false
    # 清理无效节点的时间间隔,默认60000毫秒,即60秒
    eviction-interval-timer-in-ms: 60000
