spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.126.141:8090/root/SpringCloudConfig.git
          username: root
          password: root
          search-paths: repo
          default-label: master
  application:
    name: config-server
server:
  port: 8889
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/