dubbo:
  application:
    name:  dubbo-provider
  registry:
    # 读者请换成自己的zookeeperip
    address: 192.168.135.128:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30005
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000

server:
  port: 8081
spring:
  application:
    name: dubbo-provider
